name: 多看点

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0 1 1 *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        
        DKD_duokandianBODY: ${{ DKD_duokandianBODY }}
        DKD_duokandianvideoBODY: ${{ DKD_duokandianvideoBODY }}
        DKD_duokandianCASH: ${{ DKD_duokandianCASH }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ziye66666/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_refreshTOKEN
        run: |
          cd ~/JavaScript
          npm install
      - name: '运行 【多看点】'
        if: env.XP_refreshTOKEN
        run: |
          cd ~/JavaScript
          node Task/duokandian.js
        env:
         
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
