name: 步步宝

on:
  workflow_dispatch:
  schedule:
    - cron: '*/35 0-23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/a1564471347/Scripts.git ~/Scripts
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install
          npm install cron
          npm install request
      - name: '运行 【步步宝】'
        run: |
          cd ~/Scripts   
          node Task/bububao.js
